# Generated by Django 4.1.1 on 2022-09-07 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('assigned_to', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=30)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='IT', max_length=30)),
            ],
        ),
    ]
